version: '3.8'

services:
  web:
    build: ./app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=images
    image: lmcyber470/hack_rkn_app:latest
    depends_on:
      - db
      - minio

  db:
    image: pgvector/pgvector:pg17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Optional for initial setup

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
  
  
  # nginx:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - web



volumes:
  postgres_data:
  minio_data:
